### ISSUE TITLE
Pretty-print the output

### ISSUE THREAD

**Issue by manton** [appsattic/feed2json.org#1]
Consider pretty-printing the JSON output. Since the converter links directly to the JSON, formatting it nicely would let people see what it's doing more clearly. (JSON Feed was designed to be as readable as possible.)

Thanks! Nice work.

**Comment by chilts** [comment]
I might set it as an option perhaps - pretty print as a default. I like the idea it's also compact if another machine asks for it. :) Sound good?

Thanks for opening this @manton. :)
